services:

  # An experimental webrepl for Jiiify-Presentation (v3)
  webrepl:
    image: ksclarke/jpv3-webrepl:0.1.2
    container_name: webrepl
    networks:
      - proxy
    depends_on:
      - caddy
    restart: unless-stopped

  # An audiobook service
  audiobooks:
    image: ghcr.io/advplyr/audiobookshelf:2.35.1
    container_name: audiobooks
    networks:
      - proxy
    volumes:
      - /home/ga_bot/audiobookshelf/audiobooks:/audiobooks
      - /home/ga_bot/audiobookshelf/podcasts:/podcasts
      - /home/ga_bot/audiobookshelf/config:/config
      - /home/ga_bot/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/New_York
    depends_on:
      - caddy
    restart: unless-stopped

  # A proxy server that magically handles TLS connections
  caddy:
    image: caddy:2.11.4-alpine
    container_name: caddy
    cap_add:
      - NET_ADMIN
    networks:
      - proxy
    ports:
      - "80:80"                        # HTTP
      - "443:443"                      # HTTPS
      - "443:443/udp"                  # UDP for HTTPS
      - "172.17.0.1:9999:9999"         # Admin API
    volumes:
      - /home/ga_bot/caddy:/etc/caddy  # Caddy configuration
      - caddy_data:/data               # Persistent data storage
    restart: unless-stopped

volumes:
  caddy_data:

networks:
  proxy:
