version: "3.8"

services:
  caddy:
    image: caddy:2.9.1-alpine
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"                  # HTTP
      - "443:443"                # HTTPS
      - "443:443/udp"            # UDP for HTTPS
      - "172.17.0.1:9999:9999"   # Admin API
    volumes:
      - ./caddy_conf:/etc/caddy  # Caddy configuration
      - caddy_data:/data         # Persistent data storage
    restart: unless-stopped      # Ensure the container restarts automatically

volumes:
  caddy_data:
