services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "./diun_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/New_York"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_LOG_LEVEL=info"

      # SMTP notification setup
      - "DIUN_NOTIF_MAIL_HOST=${DIUN_NOTIF_MAIL_HOST}"
      - "DIUN_NOTIF_MAIL_PORT=${DIUN_NOTIF_MAIL_PORT}"
      - "DIUN_NOTIF_MAIL_SSL=${DIUN_NOTIF_MAIL_SSL}"
      - "DIUN_NOTIF_MAIL_USERNAME=${DIUN_NOTIF_MAIL_USERNAME}"
      - "DIUN_NOTIF_MAIL_PASSWORD=${DIUN_NOTIF_MAIL_PASSWORD}"
      - "DIUN_NOTIF_MAIL_FROM=${DIUN_NOTIF_MAIL_FROM}"
      - "DIUN_NOTIF_MAIL_TO=${DIUN_NOTIF_MAIL_TO}"
    restart: unless-stopped
    depends_on:
      - caddy
  caddy:
    image: caddy:alpine
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"                  # HTTP
      - "443:443"                # HTTPS
      - "443:443/udp"            # UDP for HTTPS
      - "172.17.0.1:9999:9999"   # Admin API
    volumes:
      - ./caddy_conf:/etc/caddy  # Caddy configuration
      - caddy_data:/data         # Persistent data storage
    restart: unless-stopped      # Ensure the container restarts automatically

volumes:
  caddy_data:
