name: Site Deployment

on:
  workflow_dispatch:
  push:
    tags: [ '*' ]

jobs:
  deploy:
    name: Deploy Sites
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: SCP caddy config to server
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: Caddyfile
          target: caddy/

      - name: SCP docker-compose config to server
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: docker-compose.yml
          target: .

      - name: SSH into server and deploy the new configurations
        uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f # v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          envs: ARTIFACT_NAME,RELEASE_VERSION,REPO_OWNER
          script: |
            docker compose restart caddy
